/*
 * This file is part of Navy Decoder-Android.
 *
 * Navy Decoder-Android is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Navy Decoder-Android is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Navy Decoder-Android.  If not, see <https://www.gnu.org/licenses/>.
 *
 * Copyright (c) 2011-2024 Crash Test Dummy Limited, LLC
 */
package com.crashtestdummylimited.navydecoder.model;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.Iterator;

public class NOBCCodes implements ReferenceData {

  private final HashMap<String, String> mCodesHashMap;

  public NOBCCodes() {
    String[][] CODE_MEANING_DATA = {
        {"0000", "Transient, Patients, Prisoners, And Holdees"},
        {"0002", "Medical Department Staff Officer"},
        {"0005", "Director, Health Service Or Program"},
        {"0010", "Chairman Of Department, Teaching Program"},
        {"0020", "Health Services Department Head"},
        {"0026", "Health Services Branch Clinic Director"},
        {"0028", "Health Services Division Officer"},
        {"0030", "Health Science Research Officer"},
        {"0031", "Plans, Operations And Medical Intelligence"},
        {"0049", "Health Services Quality Assurance Coordinator"},
        {"0055", "Commanding Officer, Fleet Marine Force Company"},
        {"0101", "Internist"},
        {"0102", "General Practice Medical Officer"},
        {"0104", "Intern"},
        {"0105", "Pediatrician"},
        {"0106", "Health Services Resident"},
        {"0107", "Undersea Medical Officer"},
        {"0108", "Family Physician"},
        {"0109", "Emergency Medical Specialist"},
        {"0110", "Flight Surgeon"},
        {"0111", "Dermatologist"},
        {"0113", "Physician'S Assistant"},
        {"0115", "Psychiatrist"},
        {"0118", "Anesthesiologist"},
        {"0121", "Neurologist"},
        {"0131", "Radiologist (Diagnostic)"},
        {"0135", "Radiologist (Therapeutic)"},
        {"0140", "Nuclear Medicine Specialist"},
        {"0150", "Pathologist"},
        {"0160", "Preventive Medicine Officer"},
        {"0163", "Preventive Medicine Officer (Aerospace)"},
        {"0166", "Preventive Medicine Officer (Occupational)"},
        {"0169", "Preventive Medicine Officer (Public Health)"},
        {"0214", "General Surgeon"},
        {"0224", "Neurosurgeon"},
        {"0229", "Obstetrician‑Gynecologist"},
        {"0234", "Ophthalmologist"},
        {"0244", "Orthopedic Surgeon"},
        {"0249", "Otolaryngologist"},
        {"0254", "Plastic Surgeon"},
        {"0259", "Colon Rectal Surgeon"},
        {"0264", "Thoracic And Cardiovascular Surgeon"},
        {"0269", "Urologist"},
        {"0335", "Dental Officer General Practitioner"},
        {"0340", "Operative Dentist"},
        {"0510", "Endodontist"},
        {"0515", "Orofacial Pain"},
        {"0525", "Comprehensive Dentist"},
        {"0530", "Maxillofacial Prosthetist"},
        {"0535", "Orthodontist"},
        {"0545", "Oral And Maxillofacial Radiology"},
        {"0550", "Oral Maxillofacial Surgeon"},
        {"0560", "Periodontist"},
        {"0569", "Prosthodontist"},
        {"0575", "Public Health/Preventive Dentistry Officer"},
        {"0579", "Pediatric Dentist"},
        {"0580", "Oral Pathologist"},
        {"0800", "Health Care Administrator"},
        {"0808", "Patient Administrator"},
        {"0820", "Operations Management Officer, Medical Facility"},
        {"0822", "Medical Facilities Liaison Officer"},
        {"0840", "Biochemist"},
        {"0841", "Microbiologist"},
        {"0845", "Radiation Health Officer"},
        {"0847", "Radiation Specialist"},
        {"0848", "Physiologist"},
        {"0849", "Aerospace Physiologist"},
        {"0851", "Clinical Psychologist"},
        {"0852", "Aerospace Experimental Psychologist"},
        {"0854", "Research Psychologist"},
        {"0860", "Entomologist"},
        {"0861", "Environmental Health Officer"},
        {"0862", "Industrial Hygiene Officer"},
        {"0866", "Medical Laboratory Scientist"},
        {"0868", "Clinical Social Worker"},
        {"0871", "Occupational Audiologist"},
        {"0873", "Physical Therapist"},
        {"0874", "Occupational Therapist"},
        {"0876", "Dietitian"},
        {"0880", "Optometrist"},
        {"0887", "Pharmacist"},
        {"0892", "Podiatrist"},
        {"0904", "Critical Care Nurse"},
        {"0906", "Emergency/Trauma Nurse"},
        {"0925", "Clinical Specialist, Nursing"},
        {"0932", "Perioperative Nurse"},
        {"0944", "Professional Registered Nurse"},
        {"0952", "Nurse Anesthetist"},
        {"0963", "Primary Care Nurse Practitioner"},
        {"1005", "Accounting Officer"},
        {"1015", "Internal Review Officer"},
        {"1025", "Budget Officer"},
        {"1045", "Disbursing Officer"},
        {"1050", "Comptroller"},
        {"1105", "Mess Treasurer/Caterer"},
        {"1112", "Bachelor Quarters Manager"},
        {"1130", "Food Service Officer"},
        {"1205", "Air Traffic Officer"},
        {"1215", "Cargo Handling Officer"},
        {"1242", "Passenger Transportation Officer"},
        {"1245", "Household Goods Officer"},
        {"1272", "Transportation Logistics Officer"},
        {"1295", "Transportation Director"},
        {"1302", "Issue Control Officer"},
        {"1306", "Material Division Officer"},
        {"1345", "Naval Supply Control Officer"},
        {"1370", "Warehouse And Storage Officer"},
        {"1476", "Procurement Management Officer"},
        {"1480", "Procurement Contracting Officer"},
        {"1485", "Administrative Contracting Officer"},
        {"1490", "Contracting Professional (Dawia Certified)"},
        {"1515", "Inventory Control Methods Officer"},
        {"1530", "Stock Control Officer, Requirements"},
        {"1913", "Stores Officer"},
        {"1918", "General Supply Officer"},
        {"1920", "Equipment Program Support Officer"},
        {"1935", "Ships Store Officer"},
        {"1940", "Fuel Logistics Planning Officer"},
        {"1946", "Fuel Depot Officer"},
        {"1955", "Staff Supply Officer"},
        {"1976", "Supply Field Services Officer"},
        {"1978", "Supply Logistics Officer"},
        {"1984", "Supply Plans Officer"},
        {"1990", "Technical Supply Officer (General)"},
        {"1991", "Technical Supply Officer (Aviation)"},
        {"2050", "Mathematics Research Officer"},
        {"2070", "Physicist, General"},
        {"2085", "Statistical Data Analyst"},
        {"2090", "Chemist"},
        {"2098", "Space Projects Technologist"},
        {"2105", "Air Warfare Research Officer"},
        {"2155", "Naval Sciences Research Coordinator/Administrator"},
        {"2160", "Designated Project Manager"},
        {"2161", "Major Project Manager (Selected)"},
        {"2162", "Deputy Designated Project Manager"},
        {"2163", "Manager, Designated Project Functional Element"},
        {"2164", "Designated Project Business Administrator"},
        {"2165", "Designated Project Systems Integration Coordinator"},
        {"2166", "Designated Project Engineering Coordinator"},
        {"2167", "Designated Project Test & Evaluation Coordinator"},
        {"2168", "Designated Project Integrated Logistics System Coordinator"},
        {"2170", "Designated Project Support Officer"},
        {"2175", "Undersea Warfare Research Officer (General)"},
        {"2176", "Undersea Warfare Research Officer (Antisubmarine)"},
        {"2180", "Preoperational Test And Evaluation Officer"},
        {"2181", "Operational Test And Evaluation Officer"},
        {"2190", "Liaison Officer, Naval Research And Development"},
        {"2192", "Space Acquisition Officer"},
        {"2240", "Language Officer"},
        {"2245", "Psychological Operations Officer"},
        {"2306", "Meteorology And Oceanography (METOC) Services Officer"},
        {"2310", "Geospatial Information And Services (GI&S) Officer"},
        {"2323", "Meteorology And Oceanography Watch Officer"},
        {"2365", "Staff Meteorology And Oceanography (METOC) Officer"},
        {"2410", "Intragovernmental Inquiries Officer"},
        {"2412", "Staff Public Affairs Officer"},
        {"2415", "Historical Officer"},
        {"2425", "Visual Imagery Manager"},
        {"2430", "Press Officer"},
        {"2445", "Radio‑Television Program Officer"},
        {"2505", "General Attorney"},
        {"2510", "Administrative Law Attorney"},
        {"2515", "Admiralty Attorney"},
        {"2517", "Appellate Military Judge"},
        {"2518", "Appellate Counsel"},
        {"2520", "Claims Attorney"},
        {"2529", "International Law Attorney"},
        {"2530", "Legislative Counsel"},
        {"2535", "Legal Assistance Attorney"},
        {"2554", "Military Judge, General Courts Martial"},
        {"2556", "Military Judge, Special Courts‑Martial"},
        {"2557", "Trial Counsel"},
        {"2558", "Defense Counsel"},
        {"2559", "Capital Litigator"},
        {"2560", "Environmental Law Attorney"},
        {"2591", "Legal Officer"},
        {"2592", "Military Justice Management Officer"},
        {"2605", "Administrative Assistant"},
        {"2610", "Management Analysis And Control Officer"},
        {"2612", "Management Information Systems Officer"},
        {"2614", "Management Information Center Officer"},
        {"2615", "Administrative Officer"},
        {"2617", "Postal Officer"},
        {"2642", "Maintenance And Material Management Data Analyst"},
        {"2650", "Knowledge Management Officer"},
        {"2690", "Printing And Publications Officer"},
        {"2715", "Disaster Preparedness Officer"},
        {"2720", "Navy Emergency Preparedness Liaison Officer"},
        {"2740", "Safety Engineer"},
        {"2748", "Security Manager, Information Security Program"},
        {"2750", "Law Enforcement And Security Officer, Staff"},
        {"2765", "Nuclear, Biological, And Chemical Defense Officer"},
        {"2771", "Law Enforcement And Security Officer, Afloat"},
        {"2775", "Law Enforcement And Security Officer, Shore Activity"},
        {"2780", "Force Protection Officer Afloat"},
        {"2790", "Force Protection Officer Ashore"},
        {"3015", "Mobilization And Selection Officer"},
        {"3020", "Procurement And Recruiting Officer"},
        {"3035", "Induction And Enlistment Officer"},
        {"3036", "Selective Service System Reserved Force Officer"},
        {"3125", "Personnel Distribution Officer (General)"},
        {"3126", "Personnel Distribution Officer (Officer)"},
        {"3127", "Personnel Distribution Officer (Enlisted)"},
        {"3215", "Education/Training Planning And Program Officer (General)"},
        {"3217", "Training Planning And Program Officer (Aviation, Flight)"},
        {"3219", "Training Planning And Program Officer (Aviation, Ground)"},
        {"3220", "Leadership/Management Training Program Officer"},
        {"3230", "Educational Services Officer"},
        {"3236", "Ground School Instructor"},
        {"3240", "Officer Candidate Company Officer"},
        {"3242", "Indoctrination Training Officer"},
        {"3245", "Instructor, General"},
        {"3250", "Instructor, Technical"},
        {"3251", "Instructor, Academic"},
        {"3254", "Instructor, Academic (Social Science)"},
        {"3255", "Instructor, Academic (Physical Science)"},
        {"3260", "Instructor, Engineering"},
        {"3262", "Instructor Training Officer"},
        {"3265", "Advanced Command And Staff School Instructor"},
        {"3270", "Instructor, Naval Science"},
        {"3271", "Nuclear Weapons Instructor"},
        {"3274", "Physical Training Officer"},
        {"3277", "Professor Of Naval Science"},
        {"3283", "School Administrator"},
        {"3289", "Student"},
        {"3290", "Training Officer"},
        {"3292", "Afloat Training Officer"},
        {"3298", "Training Publications And Curriculum Officer"},
        {"3320", "Human Resource Management Officer"},
        {"3330", "Equal Opportunity Program Officer"},
        {"3412", "Brig Officer"},
        {"3415", "Discipline Administration And Review Officer"},
        {"3420", "Personnel Performance Officer (General)"},
        {"3421", "Personnel Performance Officer (Officer)"},
        {"3520", "Music Director"},
        {"3525", "Family Services Center Director"},
        {"3535", "Special Services Officer"},
        {"3701", "Chaplain Selectee"},
        {"3710", "Chaplain"},
        {"3720", "Tactical Chaplain"},
        {"3725", "Chaplain Specialist"},
        {"3730", "Supervisory Chaplain"},
        {"3740", "Group Chaplain"},
        {"3745", "Force Chaplain"},
        {"3750", "Claimant Chaplain"},
        {"3760", "Strategic/Joint Chaplain"},
        {"3910", "Transient Personnel Unit Officer"},
        {"3925", "Military Manpower Requirements Control Officer"},
        {"3943", "Manpower Planning Officer"},
        {"3950", "Personnel Research Officer"},
        {"3965", "Personnel/Manpower Management Officer"},
        {"3970", "Personnel Planning Officer"},
        {"3980", "Personnel Plans And Policy Chief"},
        {"3981", "Personnel Plans And Policy Director"},
        {"3985", "Staff Personnel Officer"},
        {"4205", "Facilities Engineering Officer"},
        {"4210", "Staff Facilities Engineer"},
        {"4215", "Facilities Planning And Programming Officer"},
        {"4220", "Facilities Design Officer"},
        {"4225", "Facilities Engineering And Acquisition"},
        {"4230", "Facilities Construction/Facilities Services Officer"},
        {"4250", "Public Works Officer"},
        {"4255", "Public Works Production Officer"},
        {"4260", "Assistant Public Works Officer"},
        {"4265", "Public Works Transportation Officer"},
        {"4270", "Public Works Utilities Officer"},
        {"4275", "Public Works Facilities Management"},
        {"4280", "Navy Contingency Engineer"},
        {"4305", "Commanding Officer, Naval Construction Forces"},
        {"4310", "Executive Officer, Naval Construction Forces"},
        {"4315", "Operations Officer, Naval Construction Forces"},
        {"4330", "Company Officer, Naval Construction Forces"},
        {"4340", "Officer In Charge, Naval Construction Battalion Unit"},
        {"4350", "Officer In Charge/Assistance Officer In Charge, Combat Service Support Team"},
        {"5761", "Training Device Program Coordinator"},
        {"5904", "Electronics Engineering Officer"},
        {"5913", "Electronic Engineering Plans And Policies Director"},
        {"5917", "Electronic Equipment Research Officer"},
        {"5925", "Electronics Installation And Maintenance Planning Officer (General)"},
        {"5927", "Electronics Installation And Maintenance Planning Officer (Aviation)"},
        {"5930", "Space Requirements Analyst"},
        {"5960", "Electronic Inspection And Survey Officer"},
        {"5961", "Aircraft Electronics Director"},
        {"5965", "Electronics Logistics Officer"},
        {"5970", "Electronic Equipment Military Characteristics Officer"},
        {"5977", "Electronic Equipment Installation, Maintenance, And Repair Officer"},
        {"5996", "Staff Electronic Material Officer"},
        {"6083", "Ammunition Material Officer"},
        {"6275", "Guided Missile Test Officer"},
        {"6280", "Guided Missile Type Project Officer (General)"},
        {"6282", "Guided Missile Type Project Officer (Ship‑Launched)"},
        {"6380", "Weapons Equipment Project Officer"},
        {"6457", "Fire Control Inspection And Repair Officer"},
        {"6470", "Weapons Control Systems Project Officer (General)"},
        {"6472", "Weapons Control Systems Project Officer (Surface)"},
        {"6516", "Mine Assembly And Repair Officer"},
        {"6537", "Torpedo Weapons Officer"},
        {"6582", "Undersea Weapons Project Officer"},
        {"6702", "Weapons Distribution Officer"},
        {"6704", "Weapons Maintenance Officer"},
        {"6715", "Weapons Material Officer (General)"},
        {"6717", "Program Manager, Weapons Systems"},
        {"6874", "Weapons Technical Information Officer"},
        {"6914", "Naval Plant Representative"},
        {"6920", "Weapons Design Officer"},
        {"6930", "Naval Weapons Technical Liaison Officer"},
        {"6936", "Weapons Systems Inspection And Survey Officer"},
        {"6938", "Weapons And Ammunition Inspection/Safety Officer"},
        {"6940", "Weapons Installation And Repair Superintendent"},
        {"6942", "Weapons Logistics Officer"},
        {"6948", "Weapons Military Characteristics Officer"},
        {"6960", "Weapons Officer, Naval Activity"},
        {"6962", "Weapons Planning And Progress Officer"},
        {"6966", "Weapons Plans And Policies Director"},
        {"6968", "Weapons And Ammunition Production Officer"},
        {"6978", "Weapons Repair Officer"},
        {"6980", "Weapons Research Planning Officer"},
        {"6982", "Weapons Technical Officer"},
        {"6990", "Weapons Safety Officer"},
        {"6999", "Staff Weapons Material Officer"},
        {"7120", "Naval Engineering Hull Development Officer"},
        {"7140", "Hull Inspection Officer"},
        {"7165", "Hull Superintendent"},
        {"7187", "Staff Hull Material Officer"},
        {"7241", "Machinery Installation And Repair Superintendent"},
        {"7249", "Nuclear Systems And Components Repair Officer, Ship"},
        {"7251", "Radiological Control Officer"},
        {"7273", "Nuclear Power Research Project Officer"},
        {"7285", "Staff Machinery Material Officer"},
        {"7420", "Ship Type Planning And Estimating Superintendent"},
        {"7435", "Quality Assurance Superintendent"},
        {"7445", "Production Engineering Officer"},
        {"7450", "Shop Production Officer"},
        {"7905", "Ship Project Officer"},
        {"7910", "Engineering Liaison Officer"},
        {"7927", "Naval Engineering Inspection Officer"},
        {"7930", "Ship Electrical Repair Officer"},
        {"7931", "Naval Engineering Logistics Officer"},
        {"7936", "Ship Construction And Repair Superintendent (General)"},
        {"7937", "Ship Construction And Repair Superintendent (Surface Ships)"},
        {"7938", "Ship Construction And Repair Superintendent (Submarines)"},
        {"7939", "Ship Construction And Repair Superintendent (Nuclear)"},
        {"7959", "Naval Engineering Research Project Officer"},
        {"7966", "Naval Engineering Trials And Survey Officer"},
        {"7968", "Nuclear Power Superintendent"},
        {"7970", "Yard Planning Officer"},
        {"7974", "Naval Engineering Officer, Ship Design"},
        {"7976", "Ship Repair Officer"},
        {"7984", "Ship Type Engineering Officer"},
        {"7996", "Supervisor Of Shipbuilding, Conversion, And Repair"},
        {"7997", "Yard Production Officer"},
        {"7998", "Combat Systems Superintendent"},
        {"7999", "Technical Assistant For Weapons"},
        {"8002", "Aerodynamics Engineering Officer"},
        {"8004", "Aeronautical Engineering Officer, Aircraft Mechanical, Electronic, Electrical, And Safety Equipment"},
        {"8015", "Aircraft Armament Development Officer"},
        {"8018", "Aircraft Production Officer"},
        {"8020", "Aircraft Survivability Officer"},
        {"8026", "Aircraft Test Engineer"},
        {"8035", "Aircraft/Guided Missile Engine Project Officer"},
        {"8050", "Launching, Recovery, And Landing Aids Engineering Officer"},
        {"8074", "Ground Support Equipment And Ship Facilities Arrangement Officer"},
        {"8076", "Type Aircraft Design And Development Officer"},
        {"8112", "Aviation Maintenance Field Representative"},
        {"8115", "Aviation Maintenance Management Engineer"},
        {"8116", "Aviation Maintenance Planning Officer"},
        {"8118", "Aviation Maintenance Engineering Officer"},
        {"8125", "Aviation Overhaul Schedules Officer"},
        {"8141", "Depot Maintenance Engineering And Quality Officer"},
        {"8152", "Depot Maintenance Production Officer"},
        {"8175", "Aircraft Intermediate Maintenance/Material Control Officer"},
        {"8176", "Aircraft Organizational Maintenance/Material Control Officer"},
        {"8177", "Aircraft Maintenance Quality Control Officer"},
        {"8180", "Air Wing Maintenance Officer"},
        {"8189", "Aircraft Intermediate Maintenance Officer, General"},
        {"8190", "Aircraft Organizational Maintenance Officer, General"},
        {"8191", "Aircraft Intermediate Maintenance Officer, Powerplants"},
        {"8192", "Aircraft Intermediate Maintenance Officer, Airframes"},
        {"8193", "Aircraft Intermediate Maintenance Officer, Armament Equipment"},
        {"8195", "Aircraft Intermediate Maintenance Officer, Support Equipment"},
        {"8196", "Aircraft Organizational Maintenance Officer, Line Division"},
        {"8197", "Aircraft Organizational Maintenance Officer, Aircraft Division"},
        {"8198", "Aircraft Intermediate Maintenance Officer, Avionics"},
        {"8199", "Aircraft Organizational Maintenance Officer, Avionics/Weapons Division"},
        {"8501", "Aviator"},
        {"8506", "Carrier Airborne Combat Information Center Officer"},
        {"8583", "Special Project Pilot"},
        {"8585", "Special Project Airborne Electronics Evaluator"},
        {"8588", "Test Pilot"},
        {"8591", "Naval Flight Officer Instructor, Training Planes"},
        {"8592", "Flight Instructor, Training Planes"},
        {"8593", "Flight Instructor ‑ Pilot, Fleet Operational Aircraft"},
        {"8594", "Flight Instructor ‑ Nfo, Fleet Operational Aircraft"},
        {"8595", "Air Vehicle Pilot Inst, Trng"},
        {"8606", "Antisubmarine Classification And Analysis Officer, Aviation"},
        {"8608", "Air Boatswain"},
        {"8614", "Catapult And Arresting Gear Officer"},
        {"8618", "Air Officer"},
        {"8620", "Air Operations Officer, Afloat"},
        {"8621", "Strike Operations Officer"},
        {"8625", "Aircraft Handling Officer"},
        {"8638", "Aircraft Fueling Officer"},
        {"8644", "Radar Air Traffic Control Center Officer"},
        {"8647", "Air Traffic Control Officer"},
        {"8653", "Officer In Charge, Aviation Unit Or Detachment"},
        {"8654", "Flight Deck Officer"},
        {"8656", "Aviation Safety Officer"},
        {"8658", "Controlled Approach Officer"},
        {"8660", "Hangar Deck Officer"},
        {"8662", "Landing Signal Officer"},
        {"8668", "Operations Officer, Aviation Shore Activity"},
        {"8670", "Squadron Commanding Officer"},
        {"8672", "Squadron Executive Officer"},
        {"8673", "Squadron Special Missions Officer"},
        {"8675", "Squadron Department Head"},
        {"8680", "Squadron Operations Officer"},
        {"8685", "Staff Air Operations And Planning Officer"},
        {"8687", "Staff Air Defense Officer"},
        {"8694", "Aviation Model Manager"},
        {"8696", "Naval Air Training And Operating Procedures Standardization Officer"},
        {"8804", "Motion Picture And Television Project Officer"},
        {"8853", "Photographic Officer"},
        {"8925", "Aircraft Material Control And Allocation Officer"},
        {"8950", "Aviation Tactical Readiness Officer"},
        {"8960", "Navy Airspace Officer"},
        {"8972", "Staff Air Tactical Officer"},
        {"8976", "Target Aircraft Controller"},
        {"8995", "Staff Aviation Safety Officer"},
        {"9005", "Commander, Operating Forces Command"},
        {"9006", "Commander, Operating Forces (Selected)"},
        {"9009", "Area Commander"},
        {"9015", "Chief Of Staff"},
        {"9016", "Chief Staff Officer"},
        {"9017", "Maritime Operations Center Director"},
        {"9018", "Convoy Commodore"},
        {"9020", "Homeland Defense Officer"},
        {"9021", "Flag Lieutenant"},
        {"9022", "Staff Fires Officer"},
        {"9023", "Maritime Space Planner"},
        {"9026", "Staff Civil Engineer"},
        {"9034", "Staff Administration Officer"},
        {"9038", "Staff Special Projects Operations Officer"},
        {"9040", "Staff Antisubmarine Officer"},
        {"9041", "Staff Current Operations Director"},
        {"9042", "Staff Combat Information Center Officer"},
        {"9043", "Staff Future Operations Director"},
        {"9044", "Cooperation And Guidance For Shipping Liaison Officer"},
        {"9045", "Staff Operations Command Center Watch Officer"},
        {"9046", "Staff Electronic Warfare Officer"},
        {"9050", "Shipping Coordination Team Officer"},
        {"9051", "Logistics Officer"},
        {"9052", "Military Assistance Programs Officer"},
        {"9053", "Staff Weapons Officer"},
        {"9056", "Staff Air Warfare Officer"},
        {"9057", "Staff Surface Warfare Officer"},
        {"9058", "Staff Theater Security Cooperation Officer"},
        {"9059", "Staff Liaison Officer"},
        {"9060", "Staff Command And Control Officer"},
        {"9061", "Staff Interagency Coordination Officer"},
        {"9062", "Amphibious Operations Officer"},
        {"9063", "Staff Material Officer"},
        {"9064", "Staff Mine Warfare Officer"},
        {"9065", "Staff Operations And Plans Officer"},
        {"9066", "Anti‑Air Warfare Operations Officer"},
        {"9067", "Staff Readiness Officer (General)"},
        {"9068", "Staff Readiness Officer (Aviation)"},
        {"9069", "Staff Readiness Officer (Weapons)"},
        {"9070", "Staff Readiness Officer (Engineering)"},
        {"9071", "Staff Readiness Officer (Seamanship)"},
        {"9072", "Staff Readiness Officer (Damage Control)"},
        {"9073", "Staff Readiness Officer (Tactics)"},
        {"9074", "Staff Readiness Officer (Communications)"},
        {"9075", "Staff Readiness Officer (Combat Information Center)"},
        {"9076", "Staff Readiness Officer (Antisubmarine Warfare)"},
        {"9077", "Staff Readiness Officer (Submarine Warfare)"},
        {"9078", "Staff Readiness Officer (Amphibious Warfare)"},
        {"9079", "Staff Readiness Officer (Electronic Warfare)"},
        {"9080", "Staff Nuclear Weapons Officer"},
        {"9082", "Flag Secretary"},
        {"9083", "Submarine Advisory Team Watch Officer"},
        {"9084", "Staff Submarine Warfare Officer"},
        {"9085", "Operations Analyst"},
        {"9086", "Strategic Plans Officer"},
        {"9087", "Staff Plans Officer"},
        {"9088", "Submarine Element Coordinator"},
        {"9089", "Operational Logistics Planner"},
        {"9090", "Operational Support Officer"},
        {"9091", "Operational Support Officer Assistant"},
        {"9092", "Assessment Director"},
        {"9093", "Assessment Analyst"},
        {"9100", "AOC Director"},
        {"9105", "AOC Chief Of Combat Plans Division"},
        {"9110", "AOC Chief Of Combat Operations Division"},
        {"9115", "AOC Chief Of Strategy Division"},
        {"9116", "AOC Strategy Team Chief"},
        {"9117", "AOC Strategy Team Member"},
        {"9120", "AOC Plans – Targeting Effects Team Chief"},
        {"9121", "AOC Plans – Targeting Effects Team Member"},
        {"9125", "AOC Plans – Master Air Attack Plan Team Chief"},
        {"9127", "AOC Plans – Master Air Attack Plan Team Member"},
        {"9130", "AOC Plans – Air Tasking Order Production Team Chief"},
        {"9131", "AOC Plans – Air Tasking Order Production Team Member"},
        {"9140", "AOC Operations – Senior Offensive Duty Officer"},
        {"9145", "AOC Senior Air Defense Officer"},
        {"9146", "AOC Senior Intelligence Duty Officer"},
        {"9148", "AOC Combat Operations Duty Officer"},
        {"9150", "AOC Dynamic Targeting Team Chief"},
        {"9151", "AOC Dynamic Targeting Team Member"},
        {"9155", "AOC Personnel Recovery Coordination Team Chief"},
        {"9156", "AOC Personnel Recovery Coordination Team Member"},
        {"9160", "AOC Special Operations Liaison Element Director"},
        {"9161", "AOC Special Operations Liaison Element Member"},
        {"9165", "AOC Chief Of Air Mobility Division"},
        {"9166", "AOC Air Mobility Division Member"},
        {"9170", "AOC Chief Of Intelligence Surveillance Reconnaissance Division"},
        {"9171", "AOC Intelligence Surveillance Reconnaissance Division Member"},
        {"9180", "AOC AADC Director And Chief Of Plans Staff Officer"},
        {"9181", "AOC AADC Chief Of Operations Staff Officer"},
        {"9182", "AADC Plans Staff Officer"},
        {"9183", "AOC AADC Operations Staff Officer"},
        {"9184", "AOC Information Operations Team Member"},
        {"9185", "AOC Airspace Control Team Member"},
        {"9190", "AOC Naval And Amphibious Liaison Element Director"},
        {"9191", "AOC Naval And Amphibious Liaison Element Member"},
        {"9193", "Naval And Ampibious Liaison Element Watch Captain"},
        {"9194", "Naval And Ampibious Liaison Element Watch Officer"},
        {"9195", "Naval And Ampibious Liaison Element Combat Plans Member"},
        {"9196", "Naval And Ampibious Liaison Element Combat Ops Member"},
        {"9197", "Naval And Ampibious Liaison Element Fires Coordinator"},
        {"9198", "Naval And Ampibious Liaison Element Deputy Director"},
        {"9199", "Naval And Ampibious Liaison Element Strategy Team Member"},
        {"9202", "Gunnery/Ordnance Officer"},
        {"9206", "Antisubmarine Weapons Officer"},
        {"9209", "Offshore Control And Surveillance System Officer"},
        {"9212", "Boat Group Officer"},
        {"9214", "Air Intercept Controller Supervisor"},
        {"9216", "Combat Information Center Officer"},
        {"9217", "Naval Tactical Data System‑‑Combat Information Center Officer"},
        {"9220", "Tactical Air Control Center Watch Officer"},
        {"9222", "Commanding Officer, Afloat"},
        {"9225", "Naval Tactical Data System‑‑Combat Information Center Watch Officer, Carrier Controlled Approach Controller"},
        {"9226", "Tactical Air Control Center Plans Officer"},
        {"9227", "Naval Tactical Data System  Combat Information Center Watch Officer, General"},
        {"9228", "Executive Officer, Afloat"},
        {"9229", "Tactical Air Control Center Detachment Officer-In-Charge"},
        {"9230", "Explosive Ordnance Disposal Officer"},
        {"9231", "Ordnance Clearance Officer"},
        {"9233", "Commanding Officer, Afloat (Lieutenant)"},
        {"9234", "Commanding Officer, Afloat (Lieutenant Commander)"},
        {"9235", "Commanding Officer, Afloat (Commander)"},
        {"9236", "Commanding Officer, Afloat (Captain)"},
        {"9237", "Fire Control Officer (General)"},
        {"9238", "Fire Control Officer (Surface‑To‑Air Missiles)"},
        {"9242", "First Lieutenant, Afloat"},
        {"9246", "Strike Warfare/Missile Systems Officer (General)"},
        {"9247", "Strike Warfare/Missile Systems Officer (Surface‑To‑Air Missiles)"},
        {"9250", "Division Officer, Weapons Department (General)"},
        {"9252", "Division Officer, Weapons Department (Gunnery)"},
        {"9255", "Surface Ship Watch/Division Officer (Basic)"},
        {"9258", "Weapons Officer (General)"},
        {"9259", "Weapons Officer (Fleet Ballistic Missiles)"},
        {"9261", "Combat Systems Officer"},
        {"9266", "Military Department Officer"},
        {"9268", "Minesweeping Officer"},
        {"9272", "Naval Gunfire Liaison Officer"},
        {"9273", "Officer In Charge, Afloat"},
        {"9274", "Operations Officer, Afloat (General)"},
        {"9275", "Operations Officer, Afloat (Naval Tactical Data Systems)"},
        {"9278", "Ship's Boatswain"},
        {"9279", "Officer In Charge, Combat Craft"},
        {"9282", "Ship's Electronic Warfare Officer"},
        {"9283", "Ship's Electronic Material Officer"},
        {"9284", "Ship's Navigator (General)"},
        {"9285", "Ship's Navigator (Inertial Systems)"},
        {"9286", "Ship's Secretary"},
        {"9287", "Department Head, Special Warfare Team"},
        {"9289", "Special Weapons Unit Officer"},
        {"9290", "Commanding Officer, Special Warfare Team"},
        {"9291", "Executive Officer, Special Warfare Team"},
        {"9293", "Sea‑Air‑Land Officer"},
        {"9294", "SEAL Delivery Vehicle Officer"},
        {"9295", "Dry Combat Submersible"},
        {"9296", "Special Weapons Assembly Officer (General)"},
        {"9302", "Auxiliary Machinery Officer"},
        {"9305", "Boiler Officer (General)"},
        {"9308", "Damage Control Assistant"},
        {"9309", "Fire Marshall"},
        {"9312", "Diving Officer (General)"},
        {"9313", "Diving Officer (Deep Sea, Heo2)"},
        {"9314", "Diving Officer (Ship Salvage)"},
        {"9315", "Diving Officer (Saturation)"},
        {"9322", "Submarine Rescue Systems Officer"},
        {"9335", "Main Propulsion Assistant (General)"},
        {"9336", "Main Propulsion Assistant (Diesel)"},
        {"9337", "Main Propulsion Assistant (Gas Turbine)"},
        {"9341", "Main Propulsion Assistant (Steam)"},
        {"9342", "Main Propulsion Assistant (1200 PSI Steam System)"},
        {"9345", "Commander, Engineering Assessment"},
        {"9348", "Repair Division Officer"},
        {"9353", "Ship's Electrical Officer"},
        {"9362", "Ship's Engineer Officer (General)"},
        {"9363", "Ship's Engineer Officer (Diesel)"},
        {"9364", "Ship's Engineer Officer (Gas Turbine)"},
        {"9369", "Ship's Engineer Officer (Steam)"},
        {"9371", "Ship's Engineer Officer, Nuclear (General)"},
        {"9372", "Ship's Engineer Officer, Nuclear (Main Propulsion)"},
        {"9373", "Ship's Engineer Officer, Nuclear (Damage Control)"},
        {"9374", "Ship's Engineer Officer, Nuclear (Electrical)"},
        {"9375", "Ship Salvage Operations Officer"},
        {"9378", "Main Engine Officer (General)"},
        {"9384", "Main Engine Officer (Steam)"},
        {"9390", "Staff Engineer Officer"},
        {"9392", "Ship's Reactor Officer"},
        {"9393", "Ship's Reactor Mechanical Assistant"},
        {"9394", "Ship's Reactor Control Assistant"},
        {"9404", "Tactical Deception Plans Officer"},
        {"9405", "Beachmaster"},
        {"9420", "Officer In Charge, Naval Shore Activity"},
        {"9421", "Commander/Commanding Officer, Shore Activity"},
        {"9422", "Commanding Officer, Naval Shore Activity (Selected)"},
        {"9430", "Drydocking Officer (General)"},
        {"9431", "Drydocking Officer (Floating Drydocks)"},
        {"9436", "Executive Officer, Shore Activity"},
        {"9442", "Facilities Manager"},
        {"9450", "Inshore Undersea Warfare Officer"},
        {"9456", "Coastal/Harbor Defense Officer"},
        {"9462", "Civil Affairs Officer"},
        {"9464", "Ocean Systems Operations Officer"},
        {"9465", "Ocean Systems Watch Officer"},
        {"9466", "Operations Officer, Ashore"},
        {"9467", "Shipping Operations Officer"},
        {"9470", "Commanding Officer, Military Sealift Command Office"},
        {"9471", "Executive Officer, Military Sealift Command Office"},
        {"9476", "Port Services Officer"},
        {"9480", "Search And Rescue Officer"},
        {"9486", "Operations Control Center Briefing Officer"},
        {"9510", "Communications Systems Center Director"},
        {"9512", "Communications Systems Current Ops Manager"},
        {"9515", "Communications Plans And Operations Officer"},
        {"9517", "Communication Security Officer"},
        {"9519", "Information Management Officer"},
        {"9523", "Joint Interface Control Officer"},
        {"9524", "Joint Data Network Operations Officer"},
        {"9525", "Communication Watch Officer"},
        {"9530", "Cryptoboard Officer"},
        {"9535", "Custodian Of Cms Material"},
        {"9543", "Director Of Communications"},
        {"9550", "Shipping Coordination Center Officer"},
        {"9555", "Defense Courier Service Officer"},
        {"9560", "Satellite Communications Officer"},
        {"9565", "Radio Officer"},
        {"9575", "Circuit Control Officer"},
        {"9580", "Communications Security Material Issuing Officer"},
        {"9582", "Information Systems Officer"},
        {"9590", "Staff Communications Officer"},
        {"9595", "Communications Traffic Officer "},
        {"9600", "Intelligence Officer Basic"},
        {"9610", "Intelligence Organization Management"},
        {"9611", "Intelligence Staff"},
        {"9613", "Intelligence Planner"},
        {"9615", "Intelligence Total Force Support"},
        {"9616", "Security Intelligence Officer "},
        {"9617", "Intelligence Investigations Officer"},
        {"9618", "Senior Intelligence Program Management"},
        {"9620", "Geographic Area Intelligence"},
        {"9631", "Navy Humint"},
        {"9632", "Defense Humint"},
        {"9635", "Naval Attache (Assistant)"},
        {"9637", "Humint Management"},
        {"9640", "Operational Intelligence Officer (General)"},
        {"9642", "Tactical Targeting Intelligence"},
        {"9644", "Joint Targeting Intelligence"},
        {"9646", "ISR Management"},
        {"9648", "ISR Management, Operational/Strategic"},
        {"9650", "Electronic Intelligence Officer"},
        {"9651", "Automatic Data Processing Intelligence Officer"},
        {"9653", "Navy Special Warfare Intelligence"},
        {"9656", "Joint Special Warfare Intelligence"},
        {"9658", "Expeditionary Intelligence"},
        {"9660", "Scientific And Technical Intelligence Officer"},
        {"9670", "Operational Intelligence (Management)"},
        {"9680", "Operational Intelligence (Analyst)"},
        {"9682", "Tactical Operations Intelligence"},
        {"9683", "Imagery Exploitation Management"},
        {"9684", "Multisensor Intelligence Officer"},
        {"9686", "Antisubmarine Warfare Intelligence Officer"},
        {"9690", "Intelligence Support To CNO/Cyber"},
        {"9705", "ADP System Director"},
        {"9710", "ADP Programs Officer"},
        {"9720", "ADP Plans Officer"},
        {"9730", "Data Base Management Officer"},
        {"9735", "Computer Systems Analyst"},
        {"9740", "Digital Computer System Programmer"},
        {"9745", "ADP Systems Maintenance Officer"},
        {"9750", "ADP Customer Liaison Officer"},
        {"9755", "Shipboard Nontactical Automatic Data Processing System Coordinator"},
        {"9781", "ADP Systems Security Officer"},
        {"9805", "Tactical Cryptologic Warfare Officer (Surface)"},
        {"9811", "Tactical Cryptologic Warfare Officer (Subsurface)"},
        {"9816", "Tactical Cryptologic Warfare Officer (Air)"},
        {"9820", "Tactical Cryptologic Warfare Officer (Special Warfare/Irregular Warfare)"},
        {"9826", "Cryptologic Warfare Officer (National)"},
        {"9831", "Cryptologic Warfare Officer (Coordinator)"},
        {"9836", "Cryptologic Warfare Officer (Planner)"},
        {"9841", "Cryptologic Warfare Officer (Staff)"},
        {"9890", "Computer Network Operations"},
        {"9891", "Computer Network Capability Development"},
        {"9905", "Atomic Energy Plans And Policies Officer"},
        {"9920", "Examiner, Reactor Safeguards"},
        {"9930", "Executive Assistant"},
        {"9935", "Aide"},
        {"9940", "Head Of Naval Mission"},
        {"9942", "International Affairs Officer"},
        {"9950", "Military Sealift Command Commander"},
        {"9960", "Inspector General"},
        {"9965", "Inspector, Technical"},
        {"9967", "Surface Safety Officer"},
        {"9970", "Plans And Policies Chief"},
        {"9975", "Foreign Disclosure Officer"},
        {"9980", "Plans And Policies Director"},
        {"9981", "Naval Plans And Policies Director, Naval Command Systems"},
        {"9990", "Joint Strategic Plans And Policy Officer"},
        {"9992", "Deputy/Vice Commander"},
        {"928A", "Division Officer, Special Warfare Team"}
    };

    mCodesHashMap = new HashMap<>(CODE_MEANING_DATA.length);

    for (String[] aCODE_MEANING_DATA : CODE_MEANING_DATA) {
      mCodesHashMap.put(aCODE_MEANING_DATA[0], aCODE_MEANING_DATA[1]);
    }
  }

  @Override
  public String getSourceInfo() {

    return "NAVPERS 15839I VOL I (JAN 2024)";
  }

  @Override
  public String getCode() {

    return "Navy Officer Billet Classification Code";
  }

  @Override
  public String[] getKeys() {

    //TO-DO:  All of this is likely not needed.  We know the # of keys so
    //        we should just be able to create a static array of that
    //        size and then copy the keys over as we iterator through them
    Iterator<String> iterator = mCodesHashMap.keySet().iterator();

    ArrayList<String> mArrayList = new ArrayList<>();

    while (iterator.hasNext()) {
      mArrayList.add(iterator.next());
    }

    Collections.sort(mArrayList);

    String[] stringArray = new String[mArrayList.size()];
    stringArray = mArrayList.toArray(stringArray);

    return stringArray;
  }

  @Override
  public String getValue(String key) {

    String returnValue;

    returnValue = mCodesHashMap.getOrDefault(key, "No match for code.");

    return returnValue;
  }

}